PATH_TO_CONFIG = "config/conf4/conf.txt"

dic = eval(open(PATH_TO_CONFIG, "r").read())

WINDOW_WIDTH = 400
WINDOW_HEIGHT = 400

DEATH_DISTANCE_BONUS = dic['DEATH_DISTANCE_BONUS'] #2
BOUNCE_BONUS = dic['BOUNCE_BONUS'] #3
WALL_PENALITY = dic['WALL_PENALITY'] #0.001
FOLLOW_BALL_BONUS = dic['FOLLOW_BALL_BONUS'] #0

POPULATION_SIZE = dic['POPULATION_SIZE'] #100
MUTATION_RATE = dic['MUTATION_RATE'] #0.01
CROSSOVER_NUMBER = dic['CROSSOVER_NUMBER'] #3
MUTATION_SCALE = dic['MUTATION_SCALE'] #-1
NB_OF_CHOSEN = dic['NB_OF_CHOSEN'] #8

LAYERS_SIZES = dic['LAYERS_SIZES']